<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Links</title>
    <style>
        <#include "css/style.css">
        <#include "css/style2.css">
    </style>
</head>
<body>
<#include "NavBar/navbar.ftlh">
<div class="content-area">
    <h1>Admin Links</h1>
</div>
<div class="background-image">
</div>
<div class="content-area">
    <div class="form-style-3">
        <div class="nav-links">
            <ul>
                <li><a href="/userdata">User Data</a></li>
                <li><a href="/ban">Ban Users</a></li>
                <li><a href="/v3/api-docs">API Documentation (JSON)</a></li>
                <li><a href="/v3/api-docs.yaml">API Documentation (YAML)</a></li>
                <li><a href="/swagger-ui/index.html">Swagger UI</a></li>
                <li><a href="/news/new">Create New nEws</a></li>
            </ul>
        </div>
    </div>
</div>
</body>
</html>