<!doctype html>
<html>
<head>
    <title>6aH BceM!!!</title>
    <style>
        <#include "css/style.css">
        <#include "css/style2.css">
    </style>
</head>
<body>
<div class="content-area">
    <h1>6aH BceM!!!</h1>
</div>
<div class="background-image">
</div>
<div class="content-area">
    <div class="form-style-3">
        <div class="nav-links">

            <form action="/ban" method="post">
                <input type="submit" value="3a6aHuTb BceX"/>
                <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
            </form>
        </div>
    </div>
</div>
</body>
</html>